repository: localhost:5000

image:
  name: kong/python
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: local

ingress:
  hosts:
    - host: localhost
      paths:
        - /