repository: localhost:5000

replicaCount: 1

autoscaling:
  enabled: false

image:
  name: kong/python
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: local

ingress:
  hosts:
    - host: localhost
      paths:
        - /

volumes:
  - name: development-volume
    mountPath: /src
    hostPath: /src

podSecurityContext:
  runAsUser: 1000